on:
  workflow_dispatch:
    inputs:
      print-out:
        description: 'Will print received input'
        required: true
        type: string
  
jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      run: echo Input is ${{ inputs.print-out}}
      
  tell-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Will tell a joke now
        uses: glebtee/writing-js-action@main