name: Create and publish Frontend packages

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ./frontend && ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache-dependency-path: .frontend/package-lock.json ./frontend/package.json
          registry-url: https://npm.pkg.github.com/
      - run: cd ./frontend && npm ci
      - name: Publish node packages
        run: npm login
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        working-directory: ./frontend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      