name: Build and push Docker images to GCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Front
        run: |
          docker build -t ghcr.io/glebtee/weatherapp-front:latest ./frontend
          echo IMAGE_ID
          docker push ghcr.io/glebtee/weatherapp-front:latest

      - name: Build and Push Back
        run: |
          docker build -t ghcr.io/glebtee/weatherapp-back:latest ./backend
          docker push ghcr.io/glebtee/weatherapp-back:latest
